# Generated by Django 4.2.3 on 2024-11-29 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_user_bairro_user_cep_user_cidade_user_complemento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='bairro',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='cidade',
            new_name='complement',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='complemento',
            new_name='neighbourhood',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='numero',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='rua',
            new_name='street',
        ),
    ]
