# Generated by Django 5.1.2 on 2024-10-25 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='phone',
            field=models.CharField(default=11942528100, max_length=15, unique=True),
            preserve_default=False,
        ),
    ]
